syntax = "proto3";

option csharp_namespace = "Mcsg.Wallet.Api.Protos";

package wallet;

service UserWalletProto {
    rpc Create (UserWalletCreateReq) returns (BaseRsp);
    rpc Delete (UserWalletDeleteReq) returns (UserWalletDeleteRsp);
    rpc GetTransactionInfo (TransactionGetReq) returns (BaseRsp);
    rpc AddAmount (UserWalletAddAmountReq) returns (BaseRsp);
}

message BaseRsp {
    bool success = 1;
    string message = 2;
    string id = 3;
    repeated TransactionProtoDto transactions = 4;
}

message UserWalletCreateReq {
    string userId = 1;
}

message UserWalletDeleteReq {
    string userId = 1;
    bool isDelete = 2;
}

message TransactionGetReq {
    string transactionId = 1;
}

message UserWalletAddAmountReq {
    string currencyUnit = 1;
    string amount = 2;
    string externalId = 3;
    string userAddress = 4;
    string lastedBlockNumber = 5;
}

message UserWalletDeleteRsp {
    bool success = 1;
    string message = 2;
}

message TransactionProtoDto {
    string transactionId = 1;
    string referenceNumber = 2;
    string amount = 3;
}
