<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>False</GenerateDocumentationFile>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AngleSharp" Version="1.1.2" />
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.14" />
        <PackageReference Include="Hangfire.Core" Version="1.8.14" />
        <PackageReference Include="Hangfire.Dashboard.BasicAuthorization" Version="1.0.2" />
        <PackageReference Include="Hangfire.MaximumConcurrentExecutions" Version="1.1.0" />
        <PackageReference Include="Hangfire.PostgreSql" Version="1.20.9" />
        <PackageReference Include="Hangfire.SqlServer" Version="1.8.14" />
        <PackageReference Include="HD.ZaloPay" Version="1.0.0" />
        <PackageReference Include="HtmlAgilityPack" Version="1.11.61" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.7" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
        <PackageReference Include="PuppeteerSharp" Version="18.0.5" />
        <PackageReference Include="SendGrid" Version="9.29.3" />
        <PackageReference Include="Twilio" Version="7.2.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Lib\Mcsg.Lib.Data.Wallet\Mcsg.Lib.Data.Wallet.csproj" />
        <ProjectReference Include="..\..\Lib\Mcsg.Lib.Data\Mcsg.Lib.Data.csproj" />
    </ItemGroup>

</Project>
