<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>False</GenerateDocumentationFile>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HD.ZaloPay" Version="1.0.0" />
        <PackageReference Include="HtmlAgilityPack" Version="1.11.64" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Lib\Mcsg.Lib.Data.Wallet\Mcsg.Lib.Data.Wallet.csproj" />
        <ProjectReference Include="..\..\Lib\Mcsg.Lib.Data\Mcsg.Lib.Data.csproj" />
    </ItemGroup>

</Project>
