# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev-1.0.0

pool:
  vmImage: 'windows-latest'

variables:
  - ${{ if startsWith(variables['build.SourceBranch'], 'refs/heads/release/v') }}:
    - group: Uat-AnalyticApi
  - ${{ elseif startsWith(variables['build.SourceBranch'], 'refs/heads/dev') }}:
    - group: Dev-AnalyticApi
  - ${{ elseif startsWith(variables['build.SourceBranch'], 'refs/tags/v') }}:
    - group: Prod-AnalyticApi
  - ${{ else }}:
    - group: Dev-AnalyticApi

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: '$(feedId)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Install swagger cli'
  inputs:
    command: custom
    custom: tool
    arguments: install swashbuckle.aspnetcore.cli --version 6.5.0 --global
    includeNuGetOrg: true
- task: CmdLine@2
  displayName: 'Generate swagger file'
  inputs:
    script: 'swagger tofile --output $(Build.ArtifactStagingDirectory)\swagger.json $(System.DefaultWorkingDirectory)\$(projectName)\bin\Release\net8.0\$(appDll) v1'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    downloadPath: '$(System.ArtifactsDirectory)'
    artifactName: 'drop'
- task: AzureAppServiceManage@0
  displayName: 'Stop AppService'
  inputs:
    azureSubscription: '$(serviceConnection)'
    Action: 'Stop Azure App Service'
    WebAppName: '$(apiAppName)'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy AppService'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '$(serviceConnection)'
    appType: 'webApp'
    WebAppName: '$(apiAppName)'
    packageForLinux: '$(System.ArtifactsDirectory)/drop/*.zip'

- task: AzureAppServiceManage@0
  displayName: 'Start AppService'
  inputs:
    azureSubscription: '$(serviceConnection)'
    Action: 'Start Azure App Service'
    WebAppName: '$(apiAppName)'
- task: apim@5
  displayName: 'Update API Management'
  inputs:
    ConnectedServiceNameARM: '$(serviceConnection)'
    ResourceGroupName: '$(resourceGroup)'
    ApiPortalName: '$(apiManagementName)'
    OpenAPISpec: 'v3'
    Format: 'json'
    Authorization: 'None'
    SwaggerPicker: 'Artifact'
    swaggerartifact: '$(System.ArtifactsDirectory)/drop/swagger.json'
    targetapi: 'AnalyticApi'
    pathapi: 'analytic'
    TemplateSelector: 'Custom'
    product1: '$(apiManagementProduct)'
    Custom: |
      <policies>
        <inbound>
            <base />
            <set-backend-service id="apim-generated-policy" base-url="$(apiManagementBackend)" />
        </inbound>
        <backend>
            <base />
        </backend>
        <outbound>
            <base />
        </outbound>
        <on-error>
            <base />
        </on-error>
      </policies>
    subscriptionRequired: false
    MicrosoftApiManagementAPIVersion: '2017-03-01'