syntax = "proto3";

option csharp_namespace = "Mcsg.Analytic.Application.Protos";

package social;

service SocialProto {
    rpc Create (SocialCreateReq) returns (SocialCreateRsp);
    rpc Update (SocialUpdateReq) returns (SocialUpdateRsp);
    rpc Delete (SocialDeleteReq) returns (SocialDeleteRsp);
}

message SocialCreateReq {
    repeated SocialProtoDto items = 1;
}

message SocialUpdateReq {
    string postId = 1;
    string body = 2;
}

message SocialDeleteReq {
    string postId = 1;
}

message SocialCreateRsp {
    bool success = 1;
    string message = 2;
    repeated SocialOutputDto items = 3;
}

message SocialUpdateRsp {
    bool success = 1;
    string message = 2;
    int64 id = 3;
}

message SocialDeleteRsp {
    bool success = 1;
    string message = 2;
    int64 id = 3;
}

message SocialProtoDto {
    string postId = 1;
    string hashId = 2;
    string userId = 3;
    string body = 4;
    string createdOn = 5;
    string createdBy = 6;
}

message SocialOutputDto {
    int64 id = 1;
}
