<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>False</GenerateDocumentationFile>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="13.0.1" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.66.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Mcsg.Common.Domain\Mcsg.Common.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\Clients\story.proto" GrpcServices="Client" />
        <Protobuf Include="Protos\Clients\story_sub.proto" GrpcServices="Client" />
    </ItemGroup>

</Project>
