// <auto-generated />
using System;
using Mcsg.Wallet.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mcsg.Wallet.Domain.Migrations
{
    [DbContext(typeof(WalletContext))]
    partial class WalletContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.EarningPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("timestamp");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Order", "FromDate", "ToDate")
                        .IsUnique();

                    b.ToTable("EarningPeriods");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.EarningSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<Guid?>("EarningPeriodId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid");

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EarningPeriodId");

                    b.HasIndex("UserId", "PeriodId")
                        .IsUnique();

                    b.ToTable("EarningSummaries");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.EarningSummaryDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<float>("DataValue")
                        .HasColumnType("real");

                    b.Property<Guid>("EarningSummaryId")
                        .HasColumnType("uuid");

                    b.Property<float>("EarningValue")
                        .HasColumnType("real");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EarningSummaryId");

                    b.ToTable("EarningSummaryDetails");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowDeposit")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowWithdrawal")
                        .HasColumnType("boolean");

                    b.Property<string>("Bin")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SelfId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserWalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserWalletId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.PremiumPackage", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("No"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FirstTimeDiscountPercent")
                        .HasColumnType("integer");

                    b.Property<float>("FirstTimePrice")
                        .HasColumnType("real");

                    b.Property<float>("FirstTimePricePerMonth")
                        .HasColumnType("real");

                    b.Property<bool>("IsPackage")
                        .HasColumnType("boolean");

                    b.Property<int>("LiveTimeDay")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("PricePerMonth")
                        .HasColumnType("real");

                    b.HasKey("No");

                    b.ToTable("PremiumPackages");

                    b.HasData(
                        new
                        {
                            No = 1,
                            Description = "1 month/ 30 days",
                            FirstTimeDiscountPercent = 49,
                            FirstTimePrice = 29000f,
                            FirstTimePricePerMonth = 29000f,
                            IsPackage = true,
                            LiveTimeDay = 30,
                            Name = "Premium package x 1 month",
                            Price = 59000f,
                            PricePerMonth = 59000f
                        },
                        new
                        {
                            No = 2,
                            Description = "3 months/ 90 days",
                            FirstTimeDiscountPercent = 49,
                            FirstTimePrice = 78000f,
                            FirstTimePricePerMonth = 26000f,
                            IsPackage = true,
                            LiveTimeDay = 90,
                            Name = "Premium package x 3 months",
                            Price = 636000f,
                            PricePerMonth = 53000f
                        },
                        new
                        {
                            No = 3,
                            Description = "6 months/ 182 days",
                            FirstTimeDiscountPercent = 49,
                            FirstTimePrice = 150000f,
                            FirstTimePricePerMonth = 25000f,
                            IsPackage = true,
                            LiveTimeDay = 182,
                            Name = "Premium package x 6 months",
                            Price = 300000f,
                            PricePerMonth = 50000f
                        },
                        new
                        {
                            No = 4,
                            Description = "12 months/ 365 days",
                            FirstTimeDiscountPercent = 49,
                            FirstTimePrice = 276000f,
                            FirstTimePricePerMonth = 23000f,
                            IsPackage = true,
                            LiveTimeDay = 365,
                            Name = "Premium package x 12 months",
                            Price = 30000f,
                            PricePerMonth = 47000f
                        },
                        new
                        {
                            No = 5,
                            Description = "Individual",
                            FirstTimeDiscountPercent = 0,
                            FirstTimePrice = 2000f,
                            FirstTimePricePerMonth = 2000f,
                            IsPackage = false,
                            LiveTimeDay = 0,
                            Name = "Individual",
                            Price = 2000f,
                            PricePerMonth = 2000f
                        });
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings", "system");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.UserPaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserWalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("UserWalletId");

                    b.ToTable("UserPaymentMethods");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.UserPremiumPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<int?>("PremiumPackageNo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp");

                    b.Property<Guid?>("UserWalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PremiumPackageNo");

                    b.HasIndex("UserWalletId");

                    b.ToTable("UserPremiumPackages");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.UserPurchaseTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AffiliateUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<Guid?>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Paymethod")
                        .HasColumnType("text");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WalletTransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletTransactionId");

                    b.HasIndex("CreatorUserId", "CreatedOn");

                    b.ToTable("UserPurchaseTransactions");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.UserWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<float>("Point")
                        .HasColumnType("real");

                    b.Property<string>("ProfileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<float>("RewardPoint")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SystemMessage")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WalletSettingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("WalletSettingId");

                    b.ToTable("UserWallets");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.WalletSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.ToTable("WalletSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2f9d301-b081-4cd8-850f-27bc996702e7"),
                            CreatedOn = new DateTime(2024, 8, 8, 18, 45, 4, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2024, 8, 8, 18, 45, 4, 0, DateTimeKind.Unspecified),
                            Name = "BC",
                            Symbol = "BC"
                        });
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.WalletSettingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WalletSettingDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f65fed1-bddc-4c7c-ba57-cb33a54542c8"),
                            CreatedOn = new DateTime(2024, 8, 8, 18, 45, 4, 0, DateTimeKind.Unspecified),
                            Description = "With draw notify list email",
                            IsDelete = false,
                            ModifiedOn = new DateTime(2024, 8, 8, 18, 45, 4, 0, DateTimeKind.Unspecified),
                            Name = "WithDrawNotify",
                            Type = 0,
                            Value = "info@bumcheo.vn"
                        });
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<Guid?>("DestinationUserWalletId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFromSystem")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("RelatedId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceUserWalletId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SystemMessage")
                        .HasColumnType("text");

                    b.Property<int?>("SystemMethod")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserPaymentMethodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DestinationUserWalletId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.HasIndex("SourceUserWalletId");

                    b.HasIndex("UserPaymentMethodId");

                    b.HasIndex("Id", "Status", "Type")
                        .IsUnique();

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.WalletTransactionOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp");

                    b.Property<string>("Otp")
                        .HasColumnType("text");

                    b.Property<string>("OtpToken")
                        .HasColumnType("text");

                    b.Property<int>("OtpType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Otp");

                    b.HasIndex("OtpToken");

                    b.HasIndex("TransactionId");

                    b.ToTable("WalletTransactionOtps");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.EarningSummary", b =>
                {
                    b.HasOne("Mcsg.Wallet.Domain.Entities.EarningPeriod", null)
                        .WithMany("EarningSummaries")
                        .HasForeignKey("EarningPeriodId");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.EarningSummaryDetail", b =>
                {
                    b.HasOne("Mcsg.Wallet.Domain.Entities.EarningSummary", "EarningSummary")
                        .WithMany("SummaryDetails")
                        .HasForeignKey("EarningSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EarningSummary");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.PaymentMethod", b =>
                {
                    b.HasOne("Mcsg.Wallet.Domain.Entities.UserWallet", null)
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserWalletId");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.UserPaymentMethod", b =>
                {
                    b.HasOne("Mcsg.Wallet.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("UserPaymentMethods")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mcsg.Wallet.Domain.Entities.UserWallet", "UserWallet")
                        .WithMany()
                        .HasForeignKey("UserWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("UserWallet");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.UserPremiumPackage", b =>
                {
                    b.HasOne("Mcsg.Wallet.Domain.Entities.PremiumPackage", "PremiumPackage")
                        .WithMany()
                        .HasForeignKey("PremiumPackageNo");

                    b.HasOne("Mcsg.Wallet.Domain.Entities.UserWallet", "UserWallet")
                        .WithMany()
                        .HasForeignKey("UserWalletId");

                    b.Navigation("PremiumPackage");

                    b.Navigation("UserWallet");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.UserPurchaseTransaction", b =>
                {
                    b.HasOne("Mcsg.Wallet.Domain.Entities.WalletTransaction", "WalletTransaction")
                        .WithMany("UserPurchaseTransactions")
                        .HasForeignKey("WalletTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WalletTransaction");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.UserWallet", b =>
                {
                    b.HasOne("Mcsg.Wallet.Domain.Entities.WalletSetting", "WalletSetting")
                        .WithMany("Wallets")
                        .HasForeignKey("WalletSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WalletSetting");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("Mcsg.Wallet.Domain.Entities.UserWallet", "DestinationUserWallet")
                        .WithMany("DestinationUserWalletTransactions")
                        .HasForeignKey("DestinationUserWalletId");

                    b.HasOne("Mcsg.Wallet.Domain.Entities.UserWallet", "SourceUserWallet")
                        .WithMany("SourceUserWalletTransactions")
                        .HasForeignKey("SourceUserWalletId");

                    b.HasOne("Mcsg.Wallet.Domain.Entities.UserPaymentMethod", "UserPaymentMethods")
                        .WithMany()
                        .HasForeignKey("UserPaymentMethodId");

                    b.Navigation("DestinationUserWallet");

                    b.Navigation("SourceUserWallet");

                    b.Navigation("UserPaymentMethods");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.WalletTransactionOtp", b =>
                {
                    b.HasOne("Mcsg.Wallet.Domain.Entities.WalletTransaction", "WalletTransaction")
                        .WithMany("WalletTransactionOtps")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WalletTransaction");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.EarningPeriod", b =>
                {
                    b.Navigation("EarningSummaries");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.EarningSummary", b =>
                {
                    b.Navigation("SummaryDetails");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("UserPaymentMethods");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.UserWallet", b =>
                {
                    b.Navigation("DestinationUserWalletTransactions");

                    b.Navigation("PaymentMethods");

                    b.Navigation("SourceUserWalletTransactions");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.WalletSetting", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("Mcsg.Wallet.Domain.Entities.WalletTransaction", b =>
                {
                    b.Navigation("UserPurchaseTransactions");

                    b.Navigation("WalletTransactionOtps");
                });
#pragma warning restore 612, 618
        }
    }
}
