<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>False</GenerateDocumentationFile>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="7.0.16" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.16" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.16">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.16" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.16">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.11" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Entities\Configurations\" />
        <Folder Include="Migrations\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Lib\Mcsg.Lib.Model\Mcsg.Lib.Model.csproj" />
    </ItemGroup>

</Project>
