syntax = "proto3";

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Mcsg.Identity.Api.Protos";

package user_recovery;

service UserRecoveryProto {
    rpc View (UserRecoveryViewReq) returns (UserRecoveryViewRsp);
    rpc Update (UserRecoveryUpdateReq) returns (UserRecoveryUpdateRsp);
}

message  UserRecoveryViewReq {
    string userId = 1;
    string otpCode =2;
}

message UserRecoveryViewRsp {
    bool success = 1;
    string message = 2;
    string id = 3;
    string secretKey = 4;
    google.protobuf.Timestamp modifiedOn = 5;
}

message UserRecoveryUpdateReq {
    string userId = 1;
    string otpCode =2;
}

message UserRecoveryUpdateRsp {
    bool success = 1;
    string message = 2;
    string id = 3;
    string data = 4;
}
