<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>False</GenerateDocumentationFile>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="13.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Mcsg.Common.Domain\Mcsg.Common.Domain.csproj" />
        <ProjectReference Include="..\Common\Mcsg.Common\Mcsg.Common.csproj" />
        <ProjectReference Include="..\Mcsg.Wallet.Domain\Mcsg.Wallet.Domain.csproj" />
    </ItemGroup>

</Project>
