// <auto-generated />
using System;
using Mcsg.Lib.Data.Analytic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mcsg.Lib.Data.Analytic.Migrations._202403
{
    [DbContext(typeof(AnalyticDbContext))]
    partial class AnalyticDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mcsg.Lib.Data.Analytic.Entities.UserViewPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("BrowserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int>("PostType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubPostId")
                        .HasColumnType("uuid");

                    b.Property<long>("TimeSpan")
                        .HasColumnType("bigint");

                    b.Property<string>("UserHashString")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "SubPostId", "AuthorId", "UserId", "UserHashString", "CreatedDate")
                        .IsUnique();

                    b.ToTable("UserViewPosts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
