// <auto-generated />
using System;
using Mcsg.Lib.Data.Wallet;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mcsg.Lib.Data.Wallet.Migrations._202401
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20240125061026_Update-related")]
    partial class Updaterelated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowDeposit")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowWithdrawal")
                        .HasColumnType("bit");

                    b.Property<string>("Bin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SelfId")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserWalletId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.PremiumPackage", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstTimeDiscountPercent")
                        .HasColumnType("int");

                    b.Property<float>("FirstTimePrice")
                        .HasColumnType("real");

                    b.Property<float>("FirstTimePricePerMonth")
                        .HasColumnType("real");

                    b.Property<int>("LiveTimeDay")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("PricePerMonth")
                        .HasColumnType("real");

                    b.HasKey("No");

                    b.ToTable("PremiumPackages");

                    b.HasData(
                        new
                        {
                            No = 1,
                            Description = "1 month/ 30 days",
                            FirstTimeDiscountPercent = 49,
                            FirstTimePrice = 29000f,
                            FirstTimePricePerMonth = 29000f,
                            LiveTimeDay = 30,
                            Name = "1 month",
                            Price = 59000f,
                            PricePerMonth = 59000f
                        },
                        new
                        {
                            No = 2,
                            Description = "3 months/ 90 days",
                            FirstTimeDiscountPercent = 49,
                            FirstTimePrice = 78000f,
                            FirstTimePricePerMonth = 26000f,
                            LiveTimeDay = 90,
                            Name = "3 months",
                            Price = 636000f,
                            PricePerMonth = 53000f
                        },
                        new
                        {
                            No = 3,
                            Description = "6 months/ 182 days",
                            FirstTimeDiscountPercent = 49,
                            FirstTimePrice = 150000f,
                            FirstTimePricePerMonth = 25000f,
                            LiveTimeDay = 182,
                            Name = "6 months",
                            Price = 300000f,
                            PricePerMonth = 50000f
                        },
                        new
                        {
                            No = 4,
                            Description = "12 months/ 365 days",
                            FirstTimeDiscountPercent = 49,
                            FirstTimePrice = 276000f,
                            FirstTimePricePerMonth = 23000f,
                            LiveTimeDay = 365,
                            Name = "12 months",
                            Price = 30000f,
                            PricePerMonth = 47000f
                        });
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.UserPaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("UserWalletId");

                    b.ToTable("UserPaymentMethods");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.UserPremiumPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PremiumPackageNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PremiumPackageNo");

                    b.HasIndex("UserWalletId");

                    b.ToTable("UserPremiumPackages");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.UserWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Point")
                        .HasColumnType("real");

                    b.Property<string>("ProfileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<float>("RewardPoint")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SystemMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WalletSettingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasFilter("[Address] IS NOT NULL");

                    b.HasIndex("WalletSettingId");

                    b.ToTable("UserWallets");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.WalletSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("WalletSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2f9d301-b081-4cd8-850f-27bc996702e7"),
                            CreatedDate = new DateTime(2023, 10, 11, 7, 33, 35, 791, DateTimeKind.Utc).AddTicks(4984),
                            IsDelete = false,
                            ModifiedDate = new DateTime(2023, 10, 11, 7, 33, 35, 791, DateTimeKind.Utc).AddTicks(4984),
                            Name = "BL Coin",
                            Symbol = "BL"
                        });
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.WalletSettingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WalletSettingDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f65fed1-bddc-4c7c-ba57-cb33a54542c8"),
                            CreatedDate = new DateTime(2023, 12, 11, 7, 33, 35, 791, DateTimeKind.Utc).AddTicks(4984),
                            Description = "With draw notify list email",
                            IsDelete = false,
                            ModifiedDate = new DateTime(2023, 12, 11, 7, 33, 35, 791, DateTimeKind.Utc).AddTicks(4984),
                            Name = "WithDrawNotify",
                            Type = 0,
                            Value = "dev@angelpj.com"
                        });
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DestinationUserWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFromSystem")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("RelatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceUserWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SystemMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserPaymentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinationUserWalletId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasFilter("[ReferenceNumber] IS NOT NULL");

                    b.HasIndex("SourceUserWalletId");

                    b.HasIndex("UserPaymentMethodId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.WalletTransactionOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Otp")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OtpToken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OtpType")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Otp");

                    b.HasIndex("OtpToken");

                    b.HasIndex("TransactionId");

                    b.ToTable("WalletTransactionOtps");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.PaymentMethod", b =>
                {
                    b.HasOne("Mcsg.Lib.Data.Wallet.Entities.UserWallet", null)
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserWalletId");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.UserPaymentMethod", b =>
                {
                    b.HasOne("Mcsg.Lib.Data.Wallet.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("UserPaymentMethods")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mcsg.Lib.Data.Wallet.Entities.UserWallet", "UserWallet")
                        .WithMany()
                        .HasForeignKey("UserWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("UserWallet");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.UserPremiumPackage", b =>
                {
                    b.HasOne("Mcsg.Lib.Data.Wallet.Entities.PremiumPackage", "PremiumPackage")
                        .WithMany()
                        .HasForeignKey("PremiumPackageNo");

                    b.HasOne("Mcsg.Lib.Data.Wallet.Entities.UserWallet", "UserWallet")
                        .WithMany()
                        .HasForeignKey("UserWalletId");

                    b.Navigation("PremiumPackage");

                    b.Navigation("UserWallet");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.UserWallet", b =>
                {
                    b.HasOne("Mcsg.Lib.Data.Wallet.Entities.WalletSetting", "WalletSetting")
                        .WithMany("Wallets")
                        .HasForeignKey("WalletSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WalletSetting");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.WalletTransaction", b =>
                {
                    b.HasOne("Mcsg.Lib.Data.Wallet.Entities.UserWallet", "DestinationUserWallet")
                        .WithMany("DestinationUserWalletTransactions")
                        .HasForeignKey("DestinationUserWalletId");

                    b.HasOne("Mcsg.Lib.Data.Wallet.Entities.UserWallet", "SourceUserWallet")
                        .WithMany("SourceUserWalletTransactions")
                        .HasForeignKey("SourceUserWalletId");

                    b.HasOne("Mcsg.Lib.Data.Wallet.Entities.UserPaymentMethod", "UserPaymentMethods")
                        .WithMany()
                        .HasForeignKey("UserPaymentMethodId");

                    b.Navigation("DestinationUserWallet");

                    b.Navigation("SourceUserWallet");

                    b.Navigation("UserPaymentMethods");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.WalletTransactionOtp", b =>
                {
                    b.HasOne("Mcsg.Lib.Data.Wallet.Entities.WalletTransaction", "WalletTransaction")
                        .WithMany("WalletTransactionOtps")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WalletTransaction");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.PaymentMethod", b =>
                {
                    b.Navigation("UserPaymentMethods");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.UserWallet", b =>
                {
                    b.Navigation("DestinationUserWalletTransactions");

                    b.Navigation("PaymentMethods");

                    b.Navigation("SourceUserWalletTransactions");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.WalletSetting", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("Mcsg.Lib.Data.Wallet.Entities.WalletTransaction", b =>
                {
                    b.Navigation("WalletTransactionOtps");
                });
#pragma warning restore 612, 618
        }
    }
}
