syntax = "proto3";

import "google/protobuf/wrappers.proto";

option csharp_namespace = "Mcsg.Analytic.Application.Protos";

package story_sub;

service StorySubProto {
    rpc Create (StorySubCreateReq) returns (StorySubCreateRsp);
    rpc Delete (StorySubDeleteReq) returns (StorySubDeleteRsp);
    rpc SortedSearch(StorySubSortedSearchReq) returns (StorySubSortedSearchRsp);
}

message StorySubCreateReq {
    repeated StorySubProtoDto items = 1;
}

message StorySubDeleteReq {
    string subPostId = 1;
}

message StorySubSortedSearchReq {
    string postId = 1;
    bool descending = 2;
    int32 pageNum = 3;
    int32 pageSize = 4;
    repeated string ids = 5;
}

message StorySubCreateRsp {
    bool success = 1;
    string message = 2;
    repeated StorySubOutputDto items = 3;
}

message StorySubDeleteRsp {
    bool success = 1;
    string message = 2;
    int64 id = 3;
}

message StorySubSortedSearchRsp {
    bool success = 1;
    string message = 2;
    repeated string ids = 3;
}

message StorySubProtoDto {
    string postId = 1;
    string subPostId = 2;
    string userId = 3;
    string createdOn = 4;
    google.protobuf.StringValue createdBy = 5;
    google.protobuf.StringValue modifiedOn = 6;
    google.protobuf.StringValue modifiedBy = 7;
}

message StorySubOutputDto {
    int64 id = 1;
}
