<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>False</GenerateDocumentationFile>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="13.0.1" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.66.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Lib\Mcsg.Lib.Common\Mcsg.Lib.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\Clients\social.proto" GrpcServices="Client" />
        <Protobuf Include="Protos\Clients\social_sub.proto" GrpcServices="Client" />
        <Protobuf Include="Protos\Clients\wallet.proto" GrpcServices="Client" />
    </ItemGroup>

</Project>
