<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>False</GenerateDocumentationFile>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
        <UserSecretsId>b18bcaac-9aaf-4145-a397-df55f09024be</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="14.0.0" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.70.0" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Mcsg.Common.Domain\Mcsg.Common.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\Clients\document.proto" GrpcServices="Client" />
        <Protobuf Include="Protos\Clients\document_sub.proto" GrpcServices="Client" />
    </ItemGroup>

</Project>
