<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>False</GenerateDocumentationFile>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NETCore.Encrypt" Version="2.1.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Lib\Mcsg.Lib.Common\Mcsg.Lib.Common.csproj" />
    </ItemGroup>

</Project>
